//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Fzrain.Core.Data;
using Fzrain.Core.Domain.Scheduler;
using Fzrain.Core.Domain.Permission;
using Fzrain.Core.Domain.Permission;
using Fzrain.Core.Domain.Permission;
using Fzrain.Core.Domain.Permission;
using Fzrain.Core.Domain.Lol;
using Fzrain.Core.Domain.Lol;
using Fzrain.Core.Domain.Lol;
using Fzrain.Core.Domain.Lol;
using Fzrain.Core.Domain.Logging;
using Fzrain.Core.Domain.Configuration;
namespace Fzrain.Web.Controllers
{
	
  public partial class TaskController : BaseListController<Task>
    {
        public TaskController(IRepository<Task> repository) : base(repository)
        {
        }
    }
	
  public partial class DepartmentController : BaseListController<Department>
    {
        public DepartmentController(IRepository<Department> repository) : base(repository)
        {
        }
    }
	
  public partial class ModuleController : BaseListController<Module>
    {
        public ModuleController(IRepository<Module> repository) : base(repository)
        {
        }
    }
	
  public partial class RoleController : BaseListController<Role>
    {
        public RoleController(IRepository<Role> repository) : base(repository)
        {
        }
    }
	
  public partial class UserController : BaseListController<User>
    {
        public UserController(IRepository<User> repository) : base(repository)
        {
        }
    }
	
  public partial class BrilliantTimeController : BaseListController<BrilliantTime>
    {
        public BrilliantTimeController(IRepository<BrilliantTime> repository) : base(repository)
        {
        }
    }
	
  public partial class ChampionInfoController : BaseListController<ChampionInfo>
    {
        public ChampionInfoController(IRepository<ChampionInfo> repository) : base(repository)
        {
        }
    }
	
  public partial class BattleController : BaseListController<Battle>
    {
        public BattleController(IRepository<Battle> repository) : base(repository)
        {
        }
    }
	
  public partial class RecordController : BaseListController<Record>
    {
        public RecordController(IRepository<Record> repository) : base(repository)
        {
        }
    }
	
  public partial class LogController : BaseListController<Log>
    {
        public LogController(IRepository<Log> repository) : base(repository)
        {
        }
    }
	
  public partial class SettingController : BaseListController<Setting>
    {
        public SettingController(IRepository<Setting> repository) : base(repository)
        {
        }
    }
}